version: "2"
services:
    backend:
       build: "./samaritan-backend"
       ports:
           - "8000:5000"
       depends_on:
           - "db"
           - "mongo"
       volumes:
           - "./samaritan-backend:/app"
    db:
       image: "postgres:latest"
       volumes:
           - "samaritan_postgress-volume"
       environment:
           POSTGRES_DB: samaritan
           POSTGRES_USER: test
           POSTGRES_PASSWORD: test
       ports:
           - 5432:5432
    mongo:
       image: "mongo:3.4.18-jessie"
       volumes:
           - "samaritan_mongo-volume"
    swagger-ui:
       image: swaggerapi/swagger-ui
       container_name: "swagger-ui"
       ports:
          - "8082:8080"
       volumes:
          - ./swagger/openapi.json:/openapi.json
       environment:
          SWAGGER_JSON: /openapi.json
    swagger-editor:
       image: swaggerapi/swagger-editor
       container_name: "swagger-editor"
       ports:
          - "8081:8080"
